name: moladtbayes
version: 0.1.0.0
verbatim:
  cabal-version: 2.2
synopsis: Chemical Algorithmic Programming
description: A library for molecular representation and probabilistic programming.
category: Development
author: Oliver Goldstein
maintainer: oliverjgoldstein@gmail.com, oliver.goldstein@cs.ox.ac.uk, sammarch2@gmail.com
license: MIT
license-file: LICENSE
extra-source-files:
  - CHANGELOG.md
  - README.md
dependencies:
  - base >= 4.13 && < 4.21
  - monad-extras
  - transformers
  - mtl
  - deepseq
  - containers
  - ghc-heap
  - megaparsec >= 9.0 && < 10.0
  - vector
  - directory
  - filepath
  - bytestring
  - binary
  - text
  - random
  - log-domain
  - statistics
  - array
  - parallel
  - massiv
  - time
  - math-functions

library:
  source-dirs: src
  exposed-modules:
    - Chem.Dietz
    - Chem.Molecule
    - Chem.Validate
    - LazyPPL
    - Constants
    - Distr
    - Group
    - Orbital
    - SlaterTypeOrbital
    - GaussianProcess
    - Chem.IO.SDF
    - Chem.IO.SMILES
    - Chem.IO.SDFTiming
    - Reaction
    - Serialisable
    - SampleMolecules
    - ExampleMolecules.Benzene
    - ExampleMolecules.BenzenePretty
    - ExampleMolecules.Diborane
    - ExampleMolecules.Ferrocene
    - ExampleMolecules.Morphine
    - PrettyBenzene
    - BenchmarkModel
  other-modules:
    - ExtraF
    - Chem.Molecule.Coordinate
  language: Haskell2010

executables:
  moladtbayes:
    main: Main.hs
    source-dirs: app
    dependencies:
      - moladtbayes
      - massiv
    language: Haskell2010
  parse-molecules:
    main: ParseMolecules.hs
    source-dirs: examples
    dependencies:
      - moladtbayes
      - massiv
    language: Haskell2010

tests:
  parser-roundtrip:
    main: Main.hs
    source-dirs: test/parser-roundtrip
    dependencies:
      - moladtbayes
      - hspec
      - containers
      - megaparsec >= 9.0 && < 10.0
      - massiv
    language: Haskell2010
  validation-properties:
    main: Main.hs
    source-dirs: test/validation-properties
    dependencies:
      - moladtbayes
      - QuickCheck
      - containers
      - massiv
    language: Haskell2010
  edge-properties:
    main: Main.hs
    source-dirs: test/edge-properties
    dependencies:
      - moladtbayes
      - QuickCheck
      - containers
      - massiv
    language: Haskell2010
  benchmark-alignment:
    main: Main.hs
    source-dirs: test/benchmark-alignment
    dependencies:
      - moladtbayes
      - hspec
      - containers
      - massiv
    language: Haskell2010
